{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "redis.common.names.fullname" .) }}
  namespace: {{ include "redis.common.names.namespace" . | quote }}
  labels: {{- include "redis.common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  annotations:
    {{- if or .Values.sentinel.service.headless.annotations .Values.commonAnnotations }}
    {{- $annotations := include "redis.common.tplvalues.merge" ( dict "values" ( list .Values.sentinel.service.headless.annotations .Values.commonAnnotations ) "context" . ) }}
    {{- include "redis.common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- include "redis.externalDNS.annotations" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  {{- if .Values.sentinel.enabled }}
  publishNotReadyAddresses: true
  {{- end }}
  ports:
    - name: tcp-redis
      port: {{ if .Values.sentinel.enabled }}{{ .Values.sentinel.service.ports.redis }}{{ else }}{{ .Values.master.service.ports.redis }}{{ end }}
      targetPort: redis
    {{- if .Values.sentinel.enabled }}
    - name: tcp-sentinel
      port: {{ .Values.sentinel.service.ports.sentinel }}
      targetPort: redis-sentinel
    {{- end }}
  selector: {{- include "redis.common.labels.matchLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
