{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.rbac.create }}
apiVersion: {{ include "redis.common.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ template "redis.common.names.fullname" . }}
  namespace: {{ include "redis.common.names.namespace" . | quote }}
  labels: {{- include "redis.common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "redis.common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "redis.common.names.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "redis.serviceAccountName" . }}
{{- end }}
