apiVersion: v2
name: nebius-k8s-applications
description: A Helm chart for Kubernetes applications
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: jupyterhub
  version: "4.0.0"
  repository: "https://hub.jupyter.org/helm-chart"
