---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gradio-ui.fullname" . }}
  labels:
{{- include "gradio-ui.labels" . | nindent 4 }}
{{- if .Values.labels }}
{{- toYaml .Values.labels | nindent 4 }}
{{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "gradio-ui.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | default "7860" }}
      targetPort: 7860
  type: {{ tpl .Values.service.type . }}
