apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "osmo.labels" . | nindent 4 }}
data:
  redis-password: {{ .Values.osmo.redisPassword | b64enc }}
