apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "osmo.labels" . | nindent 4 }}
data:
  db-password: {{ .Values.osmo.dbPassword | b64enc}}
