apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.resources.additional.storage_size }}Gi
