image:
  repository: cr.eu-north1.nebius.cloud/e00vzg8t0148cc4zex/nebius/vllm/vllm-openai
  tag: v0.8.5-ray

global:
  model: Qwen/Qwen2.5-7B-Instruct

kuberay-operator:
  image:
    repository: cr.eu-north1.nebius.cloud/e00vzg8t0148cc4zex/nebius/vllm/kuberay-operator
    tag: v1.2.2
  singleNamespaceInstall: true

gradio-ui:
  enabled: false
  image:
    repository: cr.eu-north1.nebius.cloud/e00vzg8t0148cc4zex/nebius/vllm/gradio-ui
    tag: v0.0.4
  secret:
    env:
      AUTH_USER:
      AUTH_PASSWORD:
      BASE_URL: 'http://{{ .Release.Name }}-serve-svc:8000/v1/'

gpuPerWorker: 1
gpuPlatform: NVIDIA® L40S with Intel Ice Lake
gpuToResourceHelperValues:
  NVIDIA® H100 NVLink with Intel Sapphire Rapids:
    cpu: 14500
    memory: 190
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
              - NVIDIA-H100-80GB-HBM3
        - matchExpressions:
          - key: node.kubernetes.io/instance-type
            operator: In
            values:
              - gpu-h100-sxm
  NVIDIA® H200 NVLink with Intel Sapphire Rapids:
    cpu: 14500
    memory: 190
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
              - NVIDIA-H200
        - matchExpressions:
          - key: node.kubernetes.io/instance-type
            operator: In
            values:
              - gpu-h200-sxm
  NVIDIA® B200 NVLink with Intel Emerald Rapids:
    cpu: 14500
    memory: 214
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
              - NVIDIA-B200
        - matchExpressions:
          - key: node.kubernetes.io/instance-type
            operator: In
            values:
              - gpu-b200-sxm
  NVIDIA® L40S with Intel Ice Lake:
    cpu: 4000
    memory: 24
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node.kubernetes.io/instance-type
            operator: In
            values:
              - gpu-l40s-a
  NVIDIA® L40S with AMD Genoa:
    cpu: 8000
    memory: 24
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node.kubernetes.io/instance-type
            operator: In
            values:
              - gpu-l40s-d

vllm:
  replicas: 1
  config:
    model: '{{ .Values.global.model }}'
    tensor-parallel-size: '{{ .Values.gpuPerWorker }}'
    pipeline-parallel-size: 1
    download-dir: /var/cache/huggingface
    dtype: auto
    trust-remote-code:
    distributed-executor-backend: ray
    # enforce-eager:
    # gpu-memory-utilization: 1
    enable-chunked-prefill:
    # max-num-batched-tokens: 1024
    # max-num-seqs: 1024
  hfCache:
    enabled: true
  env:
    HF_TOKEN:

worker:
  replicas: '{{ mul .Values.vllm.replicas (index .Values.vllm.config "pipeline-parallel-size") }}'
  resources:
    limits:
      cpu: "{{ mul (get .Values.gpuToResourceHelperValues .Values.gpuPlatform).cpu .Values.gpuPerWorker }}m"
      memory: "{{ mul (get .Values.gpuToResourceHelperValues .Values.gpuPlatform).memory .Values.gpuPerWorker }}Gi"
      nvidia.com/gpu: "{{ .Values.gpuPerWorker }}"
      ephemeral-storage: "100Gi"
    requests:
      cpu: "{{ tpl .Values.worker.resources.limits.cpu . }}"
      memory: "{{ tpl .Values.worker.resources.limits.memory . }}"
      nvidia.com/gpu: '{{ tpl (get .Values.worker.resources.limits "nvidia.com/gpu") . }}'
      ephemeral-storage: '{{ tpl (get .Values.worker.resources.limits "ephemeral-storage") . }}'

curl:
  image:
    repository: cr.eu-north1.nebius.cloud/e00vzg8t0148cc4zex/nebius/vllm/curl
    tag: 8.12.1

tunna-agent:
  enabled: false
  config:
    logging:
      level: error
      format: json
