apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    {{- include "generative-virtual-screening-chart.labels" . | nindent 4 }}
  name: {{ include "generative-virtual-screening-chart.fullname" . }}-ngc-registry
data:
  NGC_REGISTRY_KEY: {{ .Values.imagePullSecret.password | b64enc }}

