apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: socat-dcgm
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: socat-dcgm
  template:
    metadata:
      labels:
        app: socat-dcgm
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: socat-dcgm
        image: alpine/socat:1.8.0.0
        args: ["tcp-listen:5555,reuseaddr,fork", "tcp-connect:nvidia-dcgm:5555"]
        ports:
        - containerPort: 5555
          protocol: TCP
      restartPolicy: Always
      nodeSelector:
        nvidia.com/gpu.deploy.dcgm: "true"
