apiVersion: v1
appVersion: 2.3.4
description: Milvus is an open-source vector database built to power AI applications
  and vector similarity search.
home: https://milvus.io/
icon: https://raw.githubusercontent.com/milvus-io/docs/master/v1.0.0/assets/milvus_logo.png
keywords:
- milvus
- elastic
- vector
- search
- deploy
kubeVersion: ^1.10.0-0
maintainers:
- email: contact@milvus.io
  name: contact
  url: milvus.io
name: milvus
sources:
- https://github.com/zilliztech/milvus
version: 4.1.11
dependencies:
  - name: etcd
    version: 6.3.3
    #  repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
    repository: file://charts/etcd
    condition: etcd.enabled
    tags:
      - etcd
  - name: minio
    version: 8.0.17
    #  repository: https://zilliztech.github.io/milvus-helm
    repository: file://charts/minio
    condition: minio.enabled
    tags:
      - minio
  - name: pulsar
    version: 2.7.8
    #  repository: https://pulsar.apache.org/charts
    repository: file://charts/pulsar
    condition: pulsar.enabled
    tags:
      - pulsar
  - name: kafka
    version: 15.5.1
    #  repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
    repository: file://charts/kafka
    condition: kafka.enabled
    tags:
      - kafka
  - condition: gpu-operator.enabled
    name: gpu-operator
    repository: oci://cr.eu-north1.nebius.cloud/marketplace/nebius/nvidia-gpu-operator/chart
    version: v25.3.2
