apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fiftyone.fullname" . }}-data
  labels:
    {{- include "fiftyone.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.fiftyone.storage.size | quote }}
