apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" . }}-files
data:
{{- $hasFiles := false }}
{{- range $sidx, $storage := .Values.storages.storage }}
  {{- range $fidx, $file := $storage.files }}
    {{- $hasFiles = true }}
  {{ printf "%s-%d-%d" $storage.name $sidx $fidx }}: |-
{{ $file.content | indent 4 }}
  {{- end }}
{{- end }}
{{- if not $hasFiles }}
  {}
{{- end }}
