{{- $auths := dict }}

{{- define "extractRegistry" }}
  {{- $imageName := . }}
  {{- $registry := "https://index.docker.io/v1/" }}
  {{- if contains "/" $imageName }}
    {{- $firstPart := splitList "/" $imageName | first }}
    {{- if contains "." $firstPart }}
      {{- $registry = printf "https://%s" $firstPart }}
    {{- end }}
  {{- end }}
  {{- $registry }}
{{- end }}

{{- range .Values.containers.containers }}
  {{- if and .imageGroup.credentials.login .imageGroup.credentials.password }}
    {{- $imageName := .imageGroup.name }}
    {{- $registry := include "extractRegistry" $imageName }}
    {{- $auth := printf "%s:%s" .imageGroup.credentials.login .imageGroup.credentials.password | b64enc }}
    {{- $_ := set $auths $registry (dict "auth" $auth) }}
  {{- end }}
{{- end }}

{{- range .Values.initContainers.containers }}
  {{- if and .imageGroup.credentials.login .imageGroup.credentials.password }}
    {{- $imageName := .imageGroup.name }}
    {{- $registry := include "extractRegistry" $imageName }}
    {{- $auth := printf "%s:%s" .imageGroup.credentials.login .imageGroup.credentials.password | b64enc }}
    {{- $_ := set $auths $registry (dict "auth" $auth) }}
  {{- end }}
{{- end }}

{{- if $auths }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myapp.fullname" . }}-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": %s}" ($auths | toJson) | b64enc }}
{{- end }}