apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dstack.fullname" . }}
  labels:
    {{- include "dstack.labels" . | nindent 4 }}
data:
  config.yml: |
    projects:
    - name: main
      backends:
      - type: nebius
        projects:
        - {{ .Values.project_id }}
        creds:
          type: service_account
          service_account_id: {{ .Values.service_account }}
          public_key_id: {{ .Values.public_key_id }}
          private_key_file: /nebius/private_key.pem
