{{- if .Values.adminPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: argocd-initial-admin-secret
  namespace: {{ include "argo-cd.namespace" . }}
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" "server" "name" "argocd-initial-admin-secret") | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.adminPassword | quote }}
{{- end }}
