apiVersion: v2
name: ray-cluster
description: Helm chart for RayCluster with worker init containers and custom service
type: application
version: 0.1.0
appVersion: "2.53.0"  

dependencies:
  - name: kuberay-operator
    version: 1.5.1
    repository: "https://ray-project.github.io/kuberay-helm/"
    condition: kuberay.enabled
  - name: kube-prometheus-stack
    version: 48.2.1
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: kube-prometheus-stack.enabled
