kuberay:
  enabled: true

configuration:
  configure:
    ray_version: "2.53.0"

    ray_autoscaling:
      enable: true
      advanced:
        version: "v2"            
        upscalingMode: "Default" # "Conservative" | "Default" | "Aggressive"
        idleTimeoutSeconds: 60

    head_group:
      image: "rayproject/ray:2.53.0-py310"
      serviceType: "ClusterIP"   # "ClusterIP" | "LoadBalancer"
      advanced:
        rayStartParams:
          num_cpus: "0"
          dashboard_host: "0.0.0.0"
        resources:
          requests:
            cpu: 1
            memory: 2
          limits:
            cpu: 1
            memory: 2

    workers_group:
      groups: []

  putspec:
    yamlInput: ""

kube-prometheus-stack:
  enabled: true
  grafana:
    service:
      annotations:
        nebius.com/MarketplaceServiceAccess: title=Grafana,ssl=false,type=web,port=http-web
    grafana.ini:
      security:
        allow_embedding: true
      auth.anonymous:
        enabled: true
        org_role: Viewer
    adminPassword: "prom-operator"
  prometheus-node-exporter:
    service:
      targetPort: 9101
      port: 9101
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 50Gi
