FROM cr.ai.nebius.cloud/crng6buqs6ev01fc6sff/nebius/stable-diffusion-webui/alpine:3.19

ADD https://github.com/TencentARC/GFPGAN/releases/download/v1.3.4/GFPGANv1.4.pth models/
ADD https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth models/RealESRGAN/RealESRGAN_x4plus.pth
ADD https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.2.4/RealESRGAN_x4plus_anime_6B.pth models/RealESRGAN/RealESRGAN_x4plus_anime_6B.pth
ADD https://github.com/cszn/KAIR/releases/download/v1.0/ESRGAN.pth models/ESRGAN/ESRGAN_4x.pth
ADD https://github.com/JingyunLiang/SwinIR/releases/download/v0.0/003_realSR_BSRGAN_DFOWMFC_s64w8_SwinIR-L_x4_GAN.pth models/SwinIR/SwinIR_4x.pth
ADD https://heibox.uni-heidelberg.de/f/578df07c8fc04ffbadf3/?dl=1 models/LDSR/LDSR/model.ckpt
ADD https://heibox.uni-heidelberg.de/f/31a76b13ea27482981b4/?dl=1 models/LDSR/project.yam
ADD https://github.com/cszn/KAIR/releases/download/v1.0/scunet_color_real_gan.pth models/ScuNET/ScuNET.pth
ADD https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors models/Stable-diffusion/
ADD https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/codeformer.pth models/Codeformer/codeformer-v0.1.0.pth
ADD https://github.com/AUTOMATIC1111/TorchDeepDanbooru/releases/download/v1/model-resnet_custom_v3.pt models/torch_deepdanbooru/model-resnet_custom_v3.pt
